require('plugins.configs')
-- require('plugins.compe')
require('plugins.telescope')
require('plugins.tree')
require('plugins.diffview')
require('plugins.treesitter')
require('plugins.kommentary')
require('plugins.autopairs')
require('plugins.lualine')
require('plugins.zerolsp')
require('plugins.null')
-- require('lsp')
require('theme')
require('mappings')
